# Use Maven directly in the build stage
FROM maven:3.8.4-openjdk-17-slim AS build

WORKDIR /app

# Copy the Maven project files and dependencies
COPY pom.xml .
RUN mvn dependency:go-offline

COPY . .

RUN mvn test
